-- Run this in Supabase SQL Editor (Dashboard → SQL → New query)

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  model text not null,
  type text not null,
  color text not null,
  body_weight text not null default '',
  hose_material text,
  valve_material text,
  tags text[] not null default '{}',
  price bigint not null default 0,
  description text not null default '',
  image text not null default '',
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;

-- Public read for storefront (anon + authenticated)
drop policy if exists "products_select_public" on public.products;
create policy "products_select_public"
  on public.products for select
  using (true);

-- Writes: use SUPABASE_SERVICE_ROLE_KEY on the server (bypasses RLS).
-- Remove permissive write policies so anon keys cannot mutate data from the client.

drop policy if exists "products_insert_service" on public.products;
drop policy if exists "products_update_service" on public.products;
drop policy if exists "products_delete_service" on public.products;
