-- Run this in Supabase SQL Editor (Dashboard → SQL → New query)

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  model text not null,
  type text not null default '',
  goods_type text not null default '',
  color text not null,
  body_material text,
  handle_material text,
  body_weight text not null default '',
  package_weight text,
  cartridge_size text,
  cartridge_nut_material text,
  left_handed_nut text,
  hot_cold_output text,
  package_dimensions text,
  postal_hose text,
  escutcheon text,
  valve_material text,
  spout_material text,
  plator_material text,
  hose_material text,
  tags text[] not null default '{}',
  price bigint not null default 0,
  description text not null default '',
  image text not null default '',
  created_at timestamptz not null default now()
);

-- Migration for existing tables
alter table public.products add column if not exists goods_type text not null default '';
alter table public.products add column if not exists body_material text;
alter table public.products add column if not exists handle_material text;
alter table public.products add column if not exists package_weight text;
alter table public.products add column if not exists cartridge_size text;
alter table public.products add column if not exists cartridge_nut_material text;
alter table public.products add column if not exists left_handed_nut text;
alter table public.products add column if not exists hot_cold_output text;
alter table public.products add column if not exists package_dimensions text;
alter table public.products add column if not exists postal_hose text;
alter table public.products add column if not exists escutcheon text;
alter table public.products add column if not exists spout_material text;
alter table public.products add column if not exists plator_material text;

update public.products
set goods_type = type
where (goods_type is null or goods_type = '') and type is not null and type != '';

alter table public.products enable row level security;

drop policy if exists "products_select_public" on public.products;
create policy "products_select_public"
  on public.products for select
  using (true);

drop policy if exists "products_insert_service" on public.products;
drop policy if exists "products_update_service" on public.products;
drop policy if exists "products_delete_service" on public.products;
