-- Orders & payment tracking for Zibal (via Supabase Edge Functions)

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  customer_name text not null default '',
  customer_phone text not null default '',
  customer_email text not null default '',
  customer_address text not null default '',
  customer_note text not null default '',
  total_amount bigint not null default 0,
  status text not null default 'pending',
  zibal_track_id bigint,
  zibal_ref_number text,
  created_at timestamptz not null default now(),
  paid_at timestamptz
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint not null,
  product_model text not null default '',
  product_goods_type text not null default '',
  product_color text not null default '',
  quantity bigint not null default 1,
  unit_price bigint not null default 0
);

create index if not exists idx_orders_status on public.orders(status);
create index if not exists idx_orders_zibal_track_id on public.orders(zibal_track_id);
create index if not exists idx_order_items_order_id on public.order_items(order_id);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Public read not required; Edge Functions use service role.
-- No public insert/update policies — all writes via Edge Functions only.
