-- Production hardening: order numbers, statuses, indexes, RLS, atomic stock, bulk orders
-- Does NOT modify 20260723120000_orders_payments.sql

-- ---------------------------------------------------------------------------
-- Order number generation (server-side only, format: RB-YYYYMMDD-00001)
-- ---------------------------------------------------------------------------

create table if not exists public.order_number_counters (
  counter_date date primary key,
  counter bigint not null default 0
);

create or replace function public.generate_order_number()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_date text;
  v_counter bigint;
begin
  v_date := to_char(current_date, 'YYYYMMDD');

  insert into public.order_number_counters (counter_date, counter)
  values (current_date, 1)
  on conflict (counter_date)
  do update set counter = public.order_number_counters.counter + 1
  returning counter into v_counter;

  return 'RB-' || v_date || '-' || lpad(v_counter::text, 5, '0');
end;
$$;

revoke all on function public.generate_order_number() from public;
grant execute on function public.generate_order_number() to service_role;

-- ---------------------------------------------------------------------------
-- Extend orders table
-- ---------------------------------------------------------------------------

alter table public.orders
  add column if not exists order_number text,
  add column if not exists updated_at timestamptz not null default now();

-- Backfill order_number for existing rows (if any)
do $$
declare
  r record;
begin
  for r in
    select id from public.orders where order_number is null or order_number = ''
  loop
    update public.orders
    set order_number = public.generate_order_number()
    where id = r.id;
  end loop;
end;
$$;

create unique index if not exists idx_orders_order_number
  on public.orders (order_number);

alter table public.orders
  drop constraint if exists orders_status_check;

alter table public.orders
  add constraint orders_status_check
  check (status in (
    'pending',
    'paid',
    'processing',
    'shipped',
    'delivered',
    'cancelled',
    'failed'
  ));

-- ---------------------------------------------------------------------------
-- Triggers: order_number on insert, updated_at on update
-- ---------------------------------------------------------------------------

create or replace function public.orders_before_insert()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.order_number is null or new.order_number = '' then
    new.order_number := public.generate_order_number();
  end if;
  new.updated_at := coalesce(new.updated_at, now());
  return new;
end;
$$;

drop trigger if exists trg_orders_before_insert on public.orders;
create trigger trg_orders_before_insert
  before insert on public.orders
  for each row
  execute function public.orders_before_insert();

create or replace function public.orders_before_update()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_orders_before_update on public.orders;
create trigger trg_orders_before_update
  before update on public.orders
  for each row
  execute function public.orders_before_update();

-- ---------------------------------------------------------------------------
-- Performance indexes for admin search
-- ---------------------------------------------------------------------------

create index if not exists idx_orders_customer_phone on public.orders (customer_phone);
create index if not exists idx_orders_customer_name on public.orders (customer_name);
create index if not exists idx_orders_created_at on public.orders (created_at desc);
create index if not exists idx_orders_zibal_ref_number on public.orders (zibal_ref_number);

-- idx_orders_status and idx_orders_zibal_track_id exist in prior migration

-- ---------------------------------------------------------------------------
-- Order status history
-- ---------------------------------------------------------------------------

create table if not exists public.order_status_history (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders (id) on delete cascade,
  old_status text,
  new_status text not null,
  changed_by text not null default 'system',
  created_at timestamptz not null default now()
);

create index if not exists idx_order_status_history_order_id
  on public.order_status_history (order_id);

create index if not exists idx_order_status_history_created_at
  on public.order_status_history (created_at desc);

alter table public.order_status_history enable row level security;

create or replace function public.log_order_status_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'UPDATE' and old.status is distinct from new.status then
    insert into public.order_status_history (order_id, old_status, new_status, changed_by)
    values (
      new.id,
      old.status,
      new.status,
      coalesce(auth.uid()::text, 'system')
    );
  end if;
  return new;
end;
$$;

drop trigger if exists trg_orders_status_history on public.orders;
create trigger trg_orders_status_history
  after update of status on public.orders
  for each row
  execute function public.log_order_status_change();

-- ---------------------------------------------------------------------------
-- Bulk order requests
-- ---------------------------------------------------------------------------

create table if not exists public.bulk_order_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  company text not null default '',
  goods_type text not null,
  quantity text not null,
  note text not null default '',
  status text not null default 'pending'
    check (status in ('pending', 'contacted', 'completed', 'cancelled')),
  created_at timestamptz not null default now()
);

create index if not exists idx_bulk_order_requests_status
  on public.bulk_order_requests (status);

create index if not exists idx_bulk_order_requests_phone
  on public.bulk_order_requests (phone);

create index if not exists idx_bulk_order_requests_created_at
  on public.bulk_order_requests (created_at desc);

alter table public.bulk_order_requests enable row level security;

-- ---------------------------------------------------------------------------
-- Atomic stock deduction (prevents overselling race conditions)
-- ---------------------------------------------------------------------------

create or replace function public.deduct_product_stock(
  p_product_id bigint,
  p_quantity bigint
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rows integer;
begin
  if p_quantity is null or p_quantity <= 0 then
    raise exception 'invalid_quantity';
  end if;

  update public.products
  set stock = stock - p_quantity
  where id = p_product_id
    and stock >= p_quantity;

  get diagnostics v_rows = row_count;
  return v_rows = 1;
end;
$$;

create or replace function public.fulfill_order_stock(p_order_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  item record;
  ok boolean;
begin
  for item in
    select product_id, sum(quantity)::bigint as total_qty
    from public.order_items
    where order_id = p_order_id
    group by product_id
  loop
    ok := public.deduct_product_stock(item.product_id, item.total_qty);
    if not ok then
      raise exception 'insufficient_stock:product_%', item.product_id;
    end if;
  end loop;
end;
$$;

create or replace function public.complete_order_payment(
  p_order_id uuid,
  p_zibal_ref_number text default null
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_status text;
begin
  select status into v_status
  from public.orders
  where id = p_order_id
  for update;

  if not found then
    raise exception 'order_not_found';
  end if;

  if v_status = 'paid' then
    return 'already_paid';
  end if;

  perform public.fulfill_order_stock(p_order_id);

  update public.orders
  set
    status = 'paid',
    paid_at = now(),
    zibal_ref_number = coalesce(p_zibal_ref_number, zibal_ref_number),
    updated_at = now()
  where id = p_order_id;

  return 'paid';
end;
$$;

revoke all on function public.deduct_product_stock(bigint, bigint) from public;
revoke all on function public.fulfill_order_stock(uuid) from public;
revoke all on function public.complete_order_payment(uuid, text) from public;

grant execute on function public.deduct_product_stock(bigint, bigint) to service_role;
grant execute on function public.fulfill_order_stock(uuid) to service_role;
grant execute on function public.complete_order_payment(uuid, text) to service_role;

-- ---------------------------------------------------------------------------
-- Admin helper (Supabase Auth: app_metadata.role = 'admin')
-- ---------------------------------------------------------------------------

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
    or (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin',
    false
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.is_admin() to anon;

-- ---------------------------------------------------------------------------
-- RLS policies: deny public; allow admin read/manage via JWT role
-- Edge Functions use service_role and bypass RLS.
-- ---------------------------------------------------------------------------

-- orders
drop policy if exists "orders_admin_select" on public.orders;
create policy "orders_admin_select"
  on public.orders for select
  to authenticated
  using (public.is_admin());

drop policy if exists "orders_admin_update" on public.orders;
create policy "orders_admin_update"
  on public.orders for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- order_items
drop policy if exists "order_items_admin_select" on public.order_items;
create policy "order_items_admin_select"
  on public.order_items for select
  to authenticated
  using (public.is_admin());

-- order_status_history
drop policy if exists "order_status_history_admin_select" on public.order_status_history;
create policy "order_status_history_admin_select"
  on public.order_status_history for select
  to authenticated
  using (public.is_admin());

-- bulk_order_requests: admin read; inserts via Edge Function (service_role)
drop policy if exists "bulk_order_requests_admin_select" on public.bulk_order_requests;
create policy "bulk_order_requests_admin_select"
  on public.bulk_order_requests for select
  to authenticated
  using (public.is_admin());

drop policy if exists "bulk_order_requests_admin_update" on public.bulk_order_requests;
create policy "bulk_order_requests_admin_update"
  on public.bulk_order_requests for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());
